server:
  port: 8080

spring:
  application:
    name: logback-ecs-example

#The possible levels are, in order of precedence: TRACE, DEBUG, INFO, WARN and ERROR.
logging:
  level:
    root: ERROR
    sm-controller: DEBUG
    sm-repository: INFO
    sm: INFO
    org.springframework: INFO

  file:
    name: app-logs
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 150
      total-size-cap: 10GB


  group:
    spring: "org.springframework"
    sm-repository: "com.sm.repo"
    sm-controller: "com.sm.controller"
    sm: "com.sm"

file:
  write_json: true
